apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: argocd
type: Opaque
stringData:
  token: root

