{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.passwordSecretName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  password: {{ "changeme" | b64enc }}
  url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.db.username "changeme" "myapp" .Values.db.database | b64enc }}
{{- end}}
