name: PR Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  packages: write
  pull-requests: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Post preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-env
          message: |
            🚀 Preview will appear shortly (Argo CD syncs every ~60s).

            **URL:** https://pr-${{ github.event.pull_request.number }}.127.0.0.1.sslip.io

